spring:
  application:
    name: app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8atrn8jo6nc7383bcd0-a.oregon-postgres.render.com:5432/inventario_6kis}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:IxeQmKUHzWPyik2PVpLV6NaSAQQOLgiO}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8085}

# Configuración personalizada para la generación de tokens JWT reales
app:
  jwt:
    secret: ${APP_JWT_SECRET:40d58e146ca34d18a86595af66fdd20615926700f2b1417c9ca149f543d560a7}
    expiration: ${APP_JWT_EXPIRATION:36000000} # 10 horas en milisegundos
